# Dockerfile.dev
# Build stage
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock ./
# Sync all groups to .venv is this is .dev Dockerfile
RUN uv sync --frozen --all-groups --no-install-project
# Runtime stage
FROM python:3.12-slim-bookworm

WORKDIR /app

# Copy virtual environment
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

# Add src to PYTHONPATH to now have errors with import modules
ENV PYTHONPATH="/app/src:$PYTHONPATH"

# Copy application code
COPY src ./src

# Copy model artifacts (ONNX + tokenizer.json + classifier.joblib)
COPY models ./models

# Expose the application port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "lab11_lib.app:app", "--host", "0.0.0.0", "--port", "8000"]