AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
  LambdaExecutionRoleArn:
    Type: String

Resources:
  SentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      Role: !Ref LambdaExecutionRoleArn
      MemorySize: 512
      Timeout: 30
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: post

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/predict"